### ISSUE TITLE
Possible bug in ContactsUpdater

### ISSUE THREAD

**Issue by christophhagen** [WhisperSystems/SignalServiceKit#146]
I was looking through the code to understand how the protocol works, and I noticed something odd:

In the `ContactsUpdater`class, the `lookupIdentifiers` method will execute the `failure` handler when the set returned from `contactIntersectionWithSet` has an element count unequal to 1.

Here is the code in question:

````
[self contactIntersectionWithSet:[NSSet setWithArray:identifiers]
                             success:^(NSSet<NSString *> *_Nonnull matchedIds) {
                                 if (matchedIds.count == 1) { // Shouldn't this be < 1
                                     NSMutableArray<SignalRecipient *> *recipients = [NSMutableArray new];
                                     for (NSString *identifier in matchedIds) {
                                         [recipients addObject:[SignalRecipient recipientWithTextSecureIdentifier:identifier]];
                                     }
                                     success([recipients copy]);
                                 } else {
                                     failure(OWSErrorMakeNoSuchSignalRecipientError());
                                 }
                             }
                             failure:failure];
````

The way I understand the code this should be
`if (matchedIds.count < 1)` instead of `if (matchedIds.count == 1)`.

Maybe it is intentional to only return one recipient, but then I don't understand why the for loop is placed there, and why a set is returned instead of a single object. And the `OWSErrorMakeNoSuchSignalRecipientError` would not really be correct, if the set contains more than 1 matching IDs

**Comment by michaelkirk** [comment]
Fixed in https://github.com/WhisperSystems/SignalServiceKit/commit/f94021df9d690c9189f6cb5936e6d7af7705df06

Thanks!
