### ISSUE TITLE
OWSSingletonAssert results in assertion failure.

### ISSUE THREAD

**Issue by elland** [WhisperSystems/SignalServiceKit#193]
As you may know, we're using SignalServiceKit to secure the messaging layer of our app [Token](http://github.com/tokenbrowser/token-ios-client). We're in the process of updating our dependencies, and noticed a strange issue with `OWSSingletonAssert()`. It seems it always fails, force-quitting the app.

It's possible that this is something that did not affect the official Signal iOS app, since they're not using latest service/protocol kits?

Any help on how to fix this would be appreciated. 👍

**Comment by charlesmchen** [comment]
@Elland that assert is used to indicate that you're creating a class that's intended to be a singleton twice.  Which class is this occurring in?  There's an easy way to resolve this - just set a breakpoint at that particular singleton and assert and you'll see who is creating that singleton.

**Comment by elland** [comment]
@charlesmchen Alright, I'll give this a try. Thanks!

**Comment by elland** [comment]
@charlesmchen everything works now! 👍
