### ISSUE TITLE
SignalServiceKit Xcode 8.3.1

### ISSUE THREAD

**Issue by nikhilwhizdhavale** [WhisperSystems/SignalServiceKit#269]
Here is the problem. I get the error '25519/Curve25519.h' file not found. What am i missing
@michaelkirk

**Comment by nikhilwhizdhavale** [comment]
Resolved by removing use_frameworks!

**Comment by marwendoukh** [comment]
@nikhilwhizdhavale have you integrated SignalServiceKit ?

Your solution solved my problem but after compiling I have found this error : 
`Module 'CocoaLumberjack' not found`

Any solution ? Thanks

**Comment by marwendoukh** [comment]
The solution I found is to update CocoaPods to version 1.5.2 and then run
`pod install`
