### ISSUE TITLE
Steps towards share app extensions

### ISSUE THREAD

**Issue by guillett** [WhisperSystems/SignalServiceKit#72]
A currently missing feature of Signal on iOS is the ability to easily share images, links, etc. (cf. https://github.com/WhisperSystems/Signal-iOS/issues/650 and https://github.com/WhisperSystems/Signal-iOS/issues/1419)

I am looking at this and investigating the best way to get that feature. I am sharing my thoughts and progress here to start a conversation and make sure that we can add that feature to Signal.

So far (and to my understanding), in order to have an App extension:

- [ ] The underlying SQLite database of Signal needs to be sharable between apps (namely the Signal app and the App extension (two different binaries so different sandboxes))
- [ ] As App extensions can't use ```[UIApplication sharedApplication]```, some refactoring is required in SignalServiceKit

I have done most of the work in my repo and would like to push amended/cleaned code to the official one.

## 1 - Moving underlying database

Note: Sharable locations are managed via App Groups that are owned by registered users/groups.

- [ ] Have a working set up with the database in a shared location
- [ ] Set the project so that it is easy for developers to keep on contributing
- [ ] Ensure a smooth transition from the current location to the shared one.

Notes:
* It is a bit painful to work with App Groups.
  * Having different entitlements for DEBUG and RELEASE would probably help
  * App group names should probably not be hard coded and referred to via the embedded entitlement files.

## 2 - Allowing SignalServiceKit to be built as part of an App Extension

Some features in SignalServiceKit are not relevant/builtable for an App Extension. Those could be disabled via a macro definition. That's the approach used by AFNetworking (cf. https://github.com/AFNetworking/AFNetworking/issues/2119). A refactoring of the SignalServiceKit.podspec (addition of subspecs) seems to do the trick.

Notes:
* I *naively* put sections of code in ```#ifndef SIGNAL_SK_APP_EXTENSIONS``` and that does the trick.
* Having a clean podspec was a bit painful. For reference, I used the same approach as YapDatabase (i.e. ```s.xcconfig = { 'OTHER_CFLAGS' => '-DSIGNAL_SK_APP_EXTENSIONS' } ```)

**Comment by jooize** [comment]
Perhaps Wire's experience is of use.

https://medium.com/@wireapp/the-challenge-of-implementing-ios-share-extension-for-end-to-end-encrypted-messenger-dd33b52b1e97

**Comment by michaelkirk** [comment]
Per WhisperSystems/Signal-iOS#2341 we've moved
the SignalServiceKit codebase into the primary Signal-iOS repository at
https://github.com/WhisperSystems/Signal-iOS. As such, this repository
will no longer be updated.

Don't worry - we will continue to make updates to SignalServiceKit, and
you can continue to use it in your projects as before. The only
difference is where the code lives.

If you are using Cocoapods, staying up to date is as simple as modifying
a line in your Podfile from this:

-  pod 'SignalServiceKit', git: 'https://github.com/WhisperSystems/SignalServiceKit.git'
To this:

+  pod 'SignalServiceKit', git: 'https://github.com/WhisperSystems/Signal-iOS.git'
